---
- hosts: default
  become: true

  tasks:
  - name: install packages
    apt: name={{ item }} state=latest
    with_items:
      - python-pip
      - vim

  - name: install docker-compose
    pip: name=docker-compose state=latest

  - block:
    - file: path=/etc/systemd/system/docker.service.d state=directory
    - copy: src=docker.conf dest=/etc/systemd/system/docker.service.d/
    - copy: src=daemon.json dest=/etc/docker/
    - file: path=~vagrant/.docker state=directory
    - copy: src=docker-config.json dest=~vagrant/.docker/config.json

  - name: add additional config files
    copy: src=portainer-endpoints.json dest=/etc/portainer-endpoints.json

  - block:
    - include_role:
        name: fkrull.docker-systemd
      vars:
        name: portainer
        description: Portainer
        image: portainer/portainer:latest
        ports:
          - 9000:9000
        volumes:
          - portainer-data:/data
          - /var/run/docker.sock:/var/run/docker.sock
          - /etc/portainer-endpoints.json:/etc/portainer-endpoints.json
        cmd: --no-auth --external-endpoints=/etc/portainer-endpoints.json

    - include_role:
        name: fkrull.docker-systemd
      vars:
        name: registry
        description: Docker Registry
        image: registry:2
        ports:
          - 5000:5000
        volumes:
          - registry-data:/var/lib/registry

  - block:
    - get_url:
        url: https://raw.githubusercontent.com/fkrull/docker-qemu-user-static/master/qemu-user-static.service
        dest: /etc/systemd/system/qemu-user-static.service
    - systemd:
        name: qemu-user-static
        daemon_reload: true
        enabled: true
        state: started
