---
- hosts: default
  become: true

  tasks:
  - name: install base packages
    apt: name={{ item }} state=latest
    with_items:
      - git
      - python-pip
      - vim

  - name: install docker-compose
    pip: name=docker-compose state=latest

  - copy: src=docker.conf dest=/etc/systemd/system/docker.service.d/
  - copy: src=daemon.json dest=/etc/docker/
  - copy: src=config.json dest=~vagrant/.docker/

  - name: install docker-compose unit files
    unarchive:
      remote_src: yes
      src: https://gitlab.com/fkrull/docker-compose-unit-files/-/jobs/artifacts/master/raw/docker-compose-unit-files.tar.gz?job=package
      dest: /etc/systemd/system/

  - name: get qemu-user-static unit file
    get_url:
      url: https://raw.githubusercontent.com/fkrull/docker-qemu-user-static/master/qemu-user-static.service
      dest: /etc/systemd/system/qemu-user-static.service
  - name: enable qemu-user-static
    systemd:
      name: qemu-user-static
      daemon_reload: true
      enabled: true
      state: started

  - name: copy system containers configuration
    synchronize:
      checksum: true
      delete: yes
      group: false
      owner: false
      recursive: true
      src: system
      dest: /var/dockercompose/

  - name: start system containers
    systemd:
      daemon-reload: true
      name: docker-compose@var-dockercompose-system.service
      enabled: true
      state: reloaded
